#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zsh/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zsh/init.zsh"
fi

autoload -Uz promptinit
# set prompt
promptinit && prompt liekos
# Customize to your needs...
export EDITOR="nvim"
export VISUAL="nvim"

# Python Virtualenvs
if [ -f /usr/bin/virtualenvwrapper.sh ]; then
    source /usr/bin/virtualenvwrapper.sh
    export WORKON_HOME="~/.virtualenvs/"
fi

# Aliases
alias vim="nvim"
alias vi="vim"
alias e="vim"
alias cat="bat"
alias find="fd"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

export FZF_DEFAULT_COMMAND="fd --type f --hidden --ignore-file ~/.ignore"
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"

