#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zsh/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zsh/init.zsh"
fi

autoload -Uz promptinit
# set prompt
promptinit && prompt liekos
# Customize to your needs...
export EDITOR="nvim"
export VISUAL="nvim"
