#!/usr/bin/zsh
# vim: set syntax=shell


function prompt_shadowboxer_precmd {
    setopt LOCAL_OPTIONS
	unsetopt XTRACE KSH_ARRAYS

    _prompt_shadowboxer_pwd=$(prompt-pwd)
}


function prompt_shadowboxer_setup {
	setopt LOCAL_OPTIONS
	unsetopt XTRACE KSH_ARRAYS
	prompt_opts=(cr percent sp subst)

    autoload -Uz add-zsh-hook

    add-zsh-hook precmd prompt_shadowboxer_precmd

	if [[ $TERM = *256color* || $TERM=*rxvt* ]]; then
		_prompt_colors=(
		  "%F{9}" # Bright Orange
		  "%F{8}" # Grey
		  "%F{15}" # Lighter Grey
		)
	fi

	PROMPT='%B${_prompt_colors[1]}%n%f%b'
    PROMPT+='${_prompt_colors[3]}@%f'
    PROMPT+='%B${_prompt_colors[2]}%m%f%b '
    PROMPT+='%B${_prompt_colors[3]}→%f%b  ${_prompt_colors[1]}${_prompt_shadowboxer_pwd}%f '
    PROMPT+='${_prompt_colors[2]}❱%f${_prompt_colors[1]}❱%f${_prompt_colors[2]}❱%f ' 
}

prompt_shadowboxer_setup "$@"
