#!/usr/bin/zsh
# vim: set syntax=shell
#
# ┌┄[jack]┄(master)
# └┄%

function prompt_liekos_precmd {
    setopt LOCAL_OPTIONS
    unsetopt XTRACE KSH_ARRAYS

    # Get Git repository information.
    if (( $+functions[git-info] )); then
        git-info
    fi

    if (( $+functions[python-info] )); then
        python-info
    fi
}

function prompt_liekos_setup {

    setopt LOCAL_OPTIONS
    unsetopt XTRACE KSH_ARRAYS
    prompt_opts=(cr percent sp subst)

    autoload -Uz add-zsh-hook

    add-zsh-hook precmd prompt_liekos_precmd

    COLOUR1="02"
    COLOUR2="07"

    zstyle ':prezto:module:prompt'              managed 'yes'

    zstyle ':prezto:module:git:info'            verbose 'yes'
    zstyle ':prezto:module:git:info:dirty'      format "%F{$COLOUR2}]%f %F{red}✘%f%%b"
    zstyle ':prezto:module:git:info:clean'      format "%F{$COLOUR2}]%f %F{green}✔%f%b"
    zstyle ':prezto:module:git:info:branch'     format "%%B%F{$COLOUR2}[%f%F{$COLOUR1} %b%f"
    zstyle ':prezto:module:git:info:commit'     format "%%B%F{$COLOUR2}[%f%F{$COLOUR1} %c%f"
    zstyle ':prezto:module:git:info:position'   format "%%B%F{$COLOUR2}[%f%F{$COLOUR1} %p%f"
    zstyle ':prezto:module:git:info:keys'       format \
                               'prompt' '$(coalesce "%b" "%c") %s%C%D' \
                               'rprompt' ''

    zstyle ':prezto:module:python:info:virtualenv' format '%F{$COLOUR2}[ %%B%F{$COLOUR1}%v%b %F{$COLOUR2}]'


    PROMPT='%B┌┄%F{$COLOUR1} %c %f::%f ${git_info:+${(e)git_info[prompt]}}
└%F{$COLOUR1}┄─╼%f%b '
    RPROMPT='${python_info[virtualenv]}'
}

prompt_liekos_setup "$@"
